// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package api

// Command defines model for Command.
type Command struct {
	ShellCommand string `json:"shell_command"`
	Uuid         string `json:"uuid"`
}

// Commands defines model for Commands.
type Commands []Command

// RequestCommand defines model for RequestCommand.
type RequestCommand struct {
	Host         string `json:"host"`
	ShellCommand string `json:"shell_command"`
}

// AddCommandJSONBody defines parameters for AddCommand.
type AddCommandJSONBody RequestCommand

// AddCommandJSONRequestBody defines body for AddCommand for application/json ContentType.
type AddCommandJSONRequestBody AddCommandJSONBody
