// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package api

// Command defines model for Command.
type Command struct {
	ShellCommand string `json:"shell_command"`
	Uuid         string `json:"uuid"`
}

// Commands defines model for Commands.
type Commands []Command

// MarkCommand defines model for MarkCommand.
type MarkCommand struct {
	ExitStatus float32 `json:"exit_status"`
	Uuid       string  `json:"uuid"`
}

// RequestCommand defines model for RequestCommand.
type RequestCommand struct {
	Host         string `json:"host"`
	ShellCommand string `json:"shell_command"`
}

// AddCommandJSONBody defines parameters for AddCommand.
type AddCommandJSONBody RequestCommand

// MarkCommandDoneJSONBody defines parameters for MarkCommandDone.
type MarkCommandDoneJSONBody MarkCommand

// AddCommandJSONRequestBody defines body for AddCommand for application/json ContentType.
type AddCommandJSONRequestBody AddCommandJSONBody

// MarkCommandDoneJSONRequestBody defines body for MarkCommandDone for application/json ContentType.
type MarkCommandDoneJSONRequestBody MarkCommandDoneJSONBody
